config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, :controllers => {:registrations => "registrations/registrations"}

  post 'new_chat/:booking_id', to: "chatrooms#create", as: "new_chat"
  patch 'confirm/:id/:booking_id', to: "jobs#confirm", as: "confirm_job"
  get 'users/:id', to: "users#show", as: "users_show"
  get 'applyments/:job_id', to: "bookings#applyments", as: "applyments_index"
  get 'confirmation/:id', to: "bookings#create_confirmation", as: "booking_confirmation"
  get 'check_confirmation/:id', to: "bookings#check_confirmation", as: "check_confirmation"
  patch 'final_confirm/:id', to: "bookings#confirm", as: "final_confirmation"

  mount StripeEvent::Engine, at: '/stripe-webhooks'


  root to: 'pages#home'

  resources :jobs do
    resources :bookings, only: %i[new create]
  end

  resources :bookings, except: %i[new create] do
    resources :reviews, only: %i[new create]
  end

  resources :chatrooms, only: %i[show index] do
    resources :messages, only: :create
  end


  resources :notifications, only: :index

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end






end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings

  validates :title, presence: true
  validates :location, presence: true
  validates :date, presence: true
  validates :price, numericality: { greater_than_or_equal: 0 }
  validates :duration, presence: true

  has_one_attached :photo

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  scope :without_bookings, -> { includes(:bookings).where( bookings: {job_id: nil}) }
  scope :bookings_not_confirmed, -> { includes(:bookings).where(bookings: { confirmed: false }) }

  monetize :price_cents

  def self.category
    ["Please choose one", "Animal Care", "Child Care", "Construction", "Education", "Grocery", "Gardening", "Housekeeping", "Technology", "Logistics", "Manufacturing", "Others"]
  end

  def self.duration
    ["15 minutes", "30 minutes", "45 minutes", "1 hour", "1.5 hour", "2 hours", "2.5 hours", "3 hours", "3.5 hours", "4 hours"]
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_action :set_job, only: %i[show destroy edit update confirm]
  skip_before_action :authenticate_user!, only: :index

  def index

    if params[:my_jobs]
      @jobs = policy_scope(Job).where(user: current_user).order(created_at: :desc)
    else
      @jobs = policy_scope(Job).bookings_not_confirmed.or(policy_scope(Job).without_bookings)
      if params['filter']
        @distance = params['filter']['distance']
        @jobs = @jobs.where.not(user: current_user).near(current_user.address, params['filter']['distance'].to_i).order(created_at: :desc)
      else
        @jobs = @jobs.where.not(user: current_user).order(created_at: :desc)
      end
    end


    @markers = @jobs.geocoded.map do |job|
      {
        lat: job.latitude,
        lng: job.longitude,
        info_window: render_to_string(partial: "/jobs/info_window", locals: { job: job })
      }
    end
  end

  def new
    @job = Job.new
    authorize @job
  end

  def create
    @job = Job.new(job_params)
    @job.user = current_user
    authorize @job

    if @job.save
      redirect_to jobs_path(my_jobs: true)
    else
      render 'new'
    end
  end

  def destroy
    @job.destroy
    redirect_to jobs_path(my_jobs: true)
  end

  def update
    @job.update(job_params)
    redirect_to job_path(@job)
  end

  def confirm
    @booking = Booking.find(params[:booking_id])
    @booking.update(pending: true)
    @job.update(job_params)
    authorize @job
    redirect_to applyments_index_path(@job)
  end

  def edit
  end

  def show
    @chatroom = Chatroom.find_by(sender: current_user, recipient: @job.user)
  end

  private

  def set_job
    @job = Job.find(params[:id])
    authorize @job
  end

  def job_params
    params.require(:job).permit(:title, :details, :location, :date, :duration, :price, :rating, :category, :photo)
  end
end

app/helpers/job_helper.rb
module JobHelper
  def choose_photo(job)
    if job.photo.attached?
      cl_image_path(job.photo.key)
    else
      asset_path('random.jpg')
    end
  end
end

app/views/jobs/_all_jobs.html.erb
<div class="big-container">
  <button type="button" class="btn-orange" id="map-btn">Open map</button>
  <div class="closed-map" id="map-hide">
    <div class="map-container">
      <div class="filter">
        <%= simple_form_for :filter, url: jobs_path, method: :get, id:"filter-form" do |f| %>
          <div class="form-check-index">
            <%= f.input 'distance', input_html: { min: 1, max: 10 }, as: :range, label:false, id:'filter' %>
          </div>
          <div id="value"></div>
          <%= f.submit 'Find jobs!', class:"btn btn-orange" %>
        <% end %>
      </div>
        <div id="map"
          style="height: 75vh;width:500px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
          data-distance="<%= @distance %>">

      </div>

    </div>
  </div>
  <div class="background-container">
    <div class="container">
        <section class="section row">
    
          <% cards = 0 %>


          <% @jobs.each_with_index do |job, index| %>
            <% unless index == 0 %>
              <% if index % 6 == 0 %>

                </section>
                <section class="section row">

              <% end %>
            <% end %>

            <div class="col-6 col-sm-4">
              <%= link_to job_path(job), class:"job-link" do %>
                <div class="card-job">
                  <div class="card-photo" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= choose_photo(job) %>)">
                    <h2><%= job.title %></h2>
                  </div>
                  <div class="card-job-infos">
                    <div class="d-flex justify-content-between">
                      <div class="small-info col-4 text-center m-auto border-right h-100">
                        <p><%= job.date %></p>

                      </div>

                      <div class="small-info col-4 text-center m-auto border-right h-100">
                        <p><%= job.duration %></p>
                      </div>

                      <div class="small-info col-4 text-center m-auto h-100">
                        <p><%= job.price %> €</p>
                      </div>
                    </div>
                    
                    <% if job.user.avatar.attached? %>
                      <%= cl_image_tag job.user.avatar.key, class:"card-job-user avatar-bordered"%>
                    <% else%>
                      <%= image_tag 'profile.png', class:"card-job-user avatar-bordered"%>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </section>
        </div>
      </div>
    </div>
  </div>

app/views/jobs/_form.html.erb
  <%= simple_form_for(job) do |f| %>

        <%= f.input :title, label: 'Your job title' %>
        <%= f.input :details, as: :text, label: 'Job details', placeholder: 'All the important details about job you are offering.' %>
        <%= f.input :location, label: 'Job location' %>
        <div class="form-inline">
          <%= f.input :category, :collection=>Job.category, value: :name, include_blank: false, include_hidden: false, wrapper_html: { class: 'inline-element' }, input_html: { class: 'form-element' } %>
          <%= f.input :price, placeholder: '€', label: 'Earnings', wrapper_html: { class: 'inline-element' }, input_html: { class: 'form-element' } %>
        </div>
        <div class="form-inline">
          <%= f.input :date, as: :date, html5: true, wrapper_html: { class: 'inline-element' }, input_html: { class: 'form-element' } %>
          <%= f.input :duration, collection: Job.duration, default: Job.duration.first, wrapper_html: { class: 'inline-element' }, input_html: { class: 'form-element' } %>
        </div>
        <%= f.input :photo, as: :file %>

      <%= f.submit 'Offer your job', class:'btn-orange' %>
  <% end %>
  <div class="link">
    <%= link_to "Back", :back %>
  </div>

app/views/jobs/_info_window.html.erb
<h2><%= job.title %></h2>
<p><%= job.location %></p>

app/views/jobs/_my_jobs.html.erb
<div class="background-container">
    <div class="title">
        <h2>Jobs posted by me</h2>
    </div>
    <% if @jobs.empty? %>
      <div class="content-container">
        <div class="no-job">
            <h2>You haven't posted a job yet!</h2>
        </div>
      </div>
    <% else %>
        <% @jobs.each do |job| %>
            <div class="card-job-done">
                <div class="img-done-container">
                    <%= image_tag choose_image(job), class: "img-job-done" %>
                </div>
                <div class="job-done-info">
                    <div class="job-title">
                        <h2><%= link_to job.title, job_path(job) %></h2>
                        <p><%= job.details %></p>
                    </div>
                    <table style="width: 100%", border=1 frame="BELOW" rules="NONE">
                        <thead>
                            <tr>
                            <th>Date</th>
                            <th>Duration</th>
                            <th>Earning</th>
                            <th>Location</th>
                            <th colspan="6"></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><%= job.date %></td>
                                <td><%= job.duration %></td>
                                <td><%= job.price %> euros</td>
                                <td><%= job.location %></td>
                                <td><%= job.category %></td>

                            </tr>
                        </tbody>
                    </table>
                </div>            
                <div class="job-done-actions">
                    <div class="inline-buttons">
                        <div class="button">
                            <%= link_to 'Edit',edit_job_path(job), class:"btn-orange" %>
                        </div>
                        <div class="button">
                            <%= link_to 'Delete',job, method: :delete, data: { confirm: 'Are you sure you want to delete this?'}, class:"btn-orange" %>
                        </div>
                    </div>
                    <div class="button">
                        <%= link_to 'Applicants', applyments_index_path(job), class:"btn-orange" %>
                    </div>
                </div>
            </div>
        <% end %>
    <% end %>
</div>

app/views/jobs/edit.html.erb
<div class="form-container">
    <h2>Edit job details</h2>
    <%= render "form", job: @job %>
</div>

app/views/jobs/index.html.erb
<% if params[:my_jobs] %>
  <%= render 'my_jobs' %>
<% else %>
  <%= render 'all_jobs' %>
<% end %>

app/views/jobs/new.html.erb
<div class="form-container">
    <%= render "form", job: @job %>
</div>

app/views/jobs/show.html.erb
<div class="show-container">
    <div class="row">
        <div class="job-details">
            <div class="img-container col-2">
                <%= image_tag choose_image(@job), class: "img-job" %>
            </div>
            <div class="job-info col-10">
                <h2><%= @job.title %></h2>
                <p>Details: <%= @job.details %></p>
                <table style="width: 100%", border=1 frame="BELOW" rules="NONE">
                    <thead>
                        <tr>
                        <th>Date</th>
                        <th>Duration</th>
                        <th>Earning</th>
                        <th>Location</th>
                        <th>Category</th>
                        <th colspan="6"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><%= @job.date %></td>
                            <td><%= @job.duration %></td>
                            <td><%= @job.price %> euros</td>
                            <td><%= @job.location %></td>
                            <td><%= @job.category %></td>

                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="apply">
                <% if @job.bookings.where(user: current_user).present? %>
                        <h2>You applied!</h2>
                <% elsif @job.user == current_user %>

                <% else %>
                        <%= link_to "Apply for this job", job_bookings_path(@job), method: :post, class:"btn-orange" %>
                <% end %>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="employer-container">
            <div class="avatar-container col-2 mr-5">

                <img src= <%= choose_avatar(@job.user) %> class="card-job-user avatar-bordered">

            </div>
            <div class="employer-info col-6">
                <h2><%= @job.user.first_name %> <%= @job.user.last_name %></h2>
            <div class="title">
                <h3>Introduction</h3>
            </div>
                <p><%= @job.user.introduction %></p>
            <div class="title">
                <h3> <%= @job.user.first_name %> can help you with...</h3>
            </div>
                  <div class="employer-categories ">
                      <div class="d-flex row" >
                        <td><% @job.user.categories.each do |category| %>
                            <div class="icons d-flex col-6 row" >
                              <div class ="icons-name">
                              <p> <%= category.name %></p>
                              </div>
                              <div class="avatar-container col-6 row">
                                 <img src= <%= choose_image_category(category) %> class="card-job-user avatar-bordered" >
                              </div>


                            </div>
                            <% end %>
                        </div>
                      </td>
                  </div>
            </div>

            <div class="reviews col-4">
                <div class="title">
                    <h1>Reviews</h1>
                </div>
                <div class="scroll-reviews">

                    <% @job.user.my_reviews.each do |review| %>
                        <div class="reviewer">
                            <img src= <%= choose_avatar(review.user) %> class="card-job-user avatar-bordered">
                            <div class="reviewer-name">
                                <h4><%= review.user.first_name %></h4>
                                <% if (review.rating) %>
                                    <div class="d-flex">
                                    <% review.rating.times do %>
                                        <i class="fas fa-star"></i>

                                    <% end %>
                                    </div>
                                <% end %>
                            </div>
                            <div class="review">
                                <p><%= review.comment %></p>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
        </div>
    </div>
</div>