config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, :controllers => {:registrations => "registrations/registrations"}

  post 'new_chat/:booking_id', to: "chatrooms#create", as: "new_chat"
  patch 'confirm/:id/:booking_id', to: "jobs#confirm", as: "confirm_job"
  get 'users/:id', to: "users#show", as: "users_show"
  get 'applyments/:job_id', to: "bookings#applyments", as: "applyments_index"
  get 'confirmation/:id', to: "bookings#create_confirmation", as: "booking_confirmation"
  get 'check_confirmation/:id', to: "bookings#check_confirmation", as: "check_confirmation"
  patch 'final_confirm/:id', to: "bookings#confirm", as: "final_confirmation"

  mount StripeEvent::Engine, at: '/stripe-webhooks'


  root to: 'pages#home'

  resources :jobs do
    resources :bookings, only: %i[new create]
  end

  resources :bookings, except: %i[new create] do
    resources :reviews, only: %i[new create]
  end

  resources :chatrooms, only: %i[show index] do
    resources :messages, only: :create
  end


  resources :notifications, only: :index

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end






end

app/views/shared/_avatar_dropdown.html.erb
<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
  <%= link_to "My profile", users_show_path(current_user), class: "dropdown-item" %>
  <%= link_to "Jobs posted by me", jobs_path(my_jobs: true), class: "dropdown-item" %>
  <%= link_to "Jobs done by me", bookings_path, class: "dropdown-item" %>
  <%= link_to "Messages", chatrooms_path(), class: "dropdown-item" %>
  <%= link_to notifications_path(), class: "dropdown-item" do %> 
    <div class="nav-notifications m-0">
      <p class="m-0">Notifications</p>
      <span class="count">
      <%= current_user.notifications.unread.count %>
      </span>
    </div>
  <% end %>

  <div class="dropdown-divider"></div>
  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
    <div class="row">
        <div class="motto col-12">
            <h2>HEY!NEIGHBOUR</h2>
            <P>Find & offer small jobs in your neighbourhood!</P>
        </div>
    </div>
    <div class="row">
        <div class="footer-bottom">
            <div class="footer-social">
                <div class="footer-links">
                    <p class="pt-3 pr-3">2021 - Hey!Neighbour</p>
                    <a href="#"><i class="fab fa-github"></i></a>
                    <a href="#"><i class="fab fa-instagram"></i></a>
                    <a href="#"><i class="fab fa-facebook"></i></a>
                    <a href="#"><i class="fab fa-twitter"></i></a>
                    <a href="#"><i class="fab fa-linkedin"></i></a>
                </div>
            </div>
            <div class="footer-actions pt-3">
                <a href="#">About us | </a>
                <a href="#">Contact us | </a>
                <a href="#">Site map | </a>
            </div>
        </div>
    </div>
</div>

app/views/shared/_logged_in_nav.html.erb
<% unless current_page?(root_path) %>
  <%= render 'shared/nav_item', path: jobs_path, text: 'Look for a job' %>

  <%= render 'shared/nav_item', path: new_job_path, text: 'Offer a job' %>
<% end %>

<li class="nav-item dropdown position-relative noti-container">
  <img src= <%= choose_avatar(current_user) %> class="card-job-user avatar-bordered" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
  <% if current_user.notifications.unread.count > 0 %>
    <span class="count count-navbar position-absolute">
        <%= current_user.notifications.unread.count %>
    </span>
  <% end %>
  <%= render 'shared/avatar_dropdown' %>

</li>

app/views/shared/_logged_out_nav.html.erb
<% unless current_page?(root_path) %>
 <%= render 'shared/nav_item', path: jobs_path, text: 'Look for a job' %>

  <%= render 'shared/nav_item', path: new_job_path, text: 'Offer a job' %>
<% end %>
  <%= render 'shared/nav_item', path: new_user_registration_path, text: 'Sign up' %>
  <%= render 'shared/nav_item', path: new_user_session_path, text: 'Login' %>

app/views/shared/_logo.html.erb
<%= link_to root_path do %>
  <h2 id="logo">Hey!Neighbour</h2>
<% end %>

app/views/shared/_nav_item.html.erb
<% unless current_page?(path) %>
    <li class="nav-item">
      <%= link_to text, path, class: "nav-link" %>
    </li>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-lewagon">
  <%= render 'shared/logo' %>

   <%= render 'shared/user_menu' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</div>

app/views/shared/_user_menu.html.erb
<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <% if user_signed_in? %>
      <%= render 'shared/logged_in_nav' %>
    <% else %>
      <%= render 'shared/logged_out_nav' %>
    <% end %>
  </ul>
</div>